[[Seacas]]
arch = "aarch64"
git-tree-sha1 = "6bdf7ff4107a25736e7c9e88fe0dc7c25247b589"
os = "macos"

    [[Seacas.download]]
    sha256 = "247704ad4c246066eebcbe0876029d2b3cd153526e90a830046cdfa13d62785e"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.5+0/Seacas.v0.1.5.aarch64-apple-darwin.tar.gz"
[[Seacas]]
arch = "aarch64"
git-tree-sha1 = "ecdd10246a0be6d5a3e510e80dac02e40fe42d50"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "093be950360d092055e54fa80579f34274a9275b238becd878d9829ae956fecc"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.5+0/Seacas.v0.1.5.aarch64-linux-gnu.tar.gz"
[[Seacas]]
arch = "i686"
git-tree-sha1 = "e133ba6c10f2829247240e8de78ed77a712aeeaf"
os = "windows"

    [[Seacas.download]]
    sha256 = "c4dd9384db67b82781a3756cddc2c5f277130771be11960fc18b5322b445e71b"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.5+0/Seacas.v0.1.5.i686-w64-mingw32.tar.gz"
[[Seacas]]
arch = "x86_64"
git-tree-sha1 = "83cbfaa858d8216dc93a642b2b4cb582dc0f8377"
os = "macos"

    [[Seacas.download]]
    sha256 = "c8beccffba4d726f36a83de97b6938906d1fbbdea89a6343463dfc605f253d22"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.5+0/Seacas.v0.1.5.x86_64-apple-darwin.tar.gz"
[[Seacas]]
arch = "x86_64"
git-tree-sha1 = "e0449954dd122fe6e55a9af9fc4290aef716769a"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "6fd5352fe542614740ea6f2bbd02546cf29bd3012d9a9844e37b351dab2ab355"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.5+0/Seacas.v0.1.5.x86_64-linux-gnu.tar.gz"
[[Seacas]]
arch = "x86_64"
git-tree-sha1 = "c2c1201e4d6bfc4b46f4c9a0bc459059ca62b3b1"
os = "windows"

    [[Seacas.download]]
    sha256 = "f7dff9304dbbec2b161aa83067c48a37848ef1ac828d5b6a1bb68a31b9e66ea9"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.5+0/Seacas.v0.1.5.x86_64-w64-mingw32.tar.gz"
