[[Seacas]]
arch = "aarch64"
git-tree-sha1 = "cf9b3dde0cb9c057cd41dfb457e008abe3addccb"
os = "macos"

    [[Seacas.download]]
    sha256 = "1a4b070415176867c8592f24088ad4a76674c10a94d7db753f1e6e31bd0b2f62"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.0+0/Seacas.v0.1.0.aarch64-apple-darwin.tar.gz"
[[Seacas]]
arch = "aarch64"
git-tree-sha1 = "0f9791ab426edb7bb7870253082cacf068639d69"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "aad9eed4dd63889182105de9217208037c98f70dd317a0a4c8148d56f27c7f92"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.0+0/Seacas.v0.1.0.aarch64-linux-gnu.tar.gz"
[[Seacas]]
arch = "i686"
git-tree-sha1 = "d6eac07dc8bc5d588e226a9ca18f932a5a739b29"
os = "windows"

    [[Seacas.download]]
    sha256 = "bd3bf66e14ed37d11aa66eb5cf3b68a4b19483afc2fb535654afb5e739d1c63b"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.0+0/Seacas.v0.1.0.i686-w64-mingw32.tar.gz"
[[Seacas]]
arch = "x86_64"
git-tree-sha1 = "759c3c6d9032e6776b59e8a8acdddf76a6d4b52c"
os = "macos"

    [[Seacas.download]]
    sha256 = "f457d8cbf5f81bc0a9d2e3913d812575f150b0f25ed763fdac8dc77e193f93fa"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.0+0/Seacas.v0.1.0.x86_64-apple-darwin.tar.gz"
[[Seacas]]
arch = "x86_64"
git-tree-sha1 = "e34ac2b94c7a4bbfdc35e3f62209a4be944808c1"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "0ba87286875fb416ea1bee0bf9868646c671579291b789084a8aea0d9a113867"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.0+0/Seacas.v0.1.0.x86_64-linux-gnu.tar.gz"
[[Seacas]]
arch = "x86_64"
git-tree-sha1 = "a4daadead93165ea78e5bf83bc120d699e2ea577"
os = "windows"

    [[Seacas.download]]
    sha256 = "1f7440a205e8d414520c48ec153bdbf43ccba7b9d0f68a26bf2804baf9a45c24"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.0+0/Seacas.v0.1.0.x86_64-w64-mingw32.tar.gz"
