[[Seacas]]
arch = "aarch64"
git-tree-sha1 = "ecdd10246a0be6d5a3e510e80dac02e40fe42d50"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "093be950360d092055e54fa80579f34274a9275b238becd878d9829ae956fecc"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.5+0/Seacas.v0.1.5.aarch64-linux-gnu.tar.gz"
[[Seacas]]
arch = "i686"
git-tree-sha1 = "e133ba6c10f2829247240e8de78ed77a712aeeaf"
os = "windows"

    [[Seacas.download]]
    sha256 = "c4dd9384db67b82781a3756cddc2c5f277130771be11960fc18b5322b445e71b"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.5+0/Seacas.v0.1.5.i686-w64-mingw32.tar.gz"
[[Seacas]]
arch = "x86_64"
git-tree-sha1 = "e0449954dd122fe6e55a9af9fc4290aef716769a"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "6fd5352fe542614740ea6f2bbd02546cf29bd3012d9a9844e37b351dab2ab355"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.5+0/Seacas.v0.1.5.x86_64-linux-gnu.tar.gz"
[[Seacas]]
arch = "x86_64"
git-tree-sha1 = "c2c1201e4d6bfc4b46f4c9a0bc459059ca62b3b1"
os = "windows"

    [[Seacas.download]]
    sha256 = "f7dff9304dbbec2b161aa83067c48a37848ef1ac828d5b6a1bb68a31b9e66ea9"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.5+0/Seacas.v0.1.5.x86_64-w64-mingw32.tar.gz"
[[Seacas]]
arch = "aarch64"
git-tree-sha1 = "b209064bf500420bf65edf80622711ff6c0720a1"
os = "macos"

    [[Seacas.download]]
    sha256 = "c95fd30fa63ee0c0aac97db7411b2e7624afa57dfe4c3c60e7433ce6418cd970"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.7+0/Seacas.v0.1.7.aarch64-apple-darwin.tar.gz"
[[Seacas]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2776c7eff8aa55b008f1a5afc09e0e0fee9f3a6c"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "722116ac4eb71db8c7070fc642729f0723541f24998565fc37953b885bdd494f"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.7+0/Seacas.v0.1.7.aarch64-linux-gnu-cxx03.tar.gz"
[[Seacas]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df23262ddc0d08d423c47ff26c36f3b06563f3d3"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "d5f0deec08b436598f8adc20976a5b3a15b11772f1c3afc73130a2d8422b8ddb"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.7+0/Seacas.v0.1.7.aarch64-linux-gnu-cxx11.tar.gz"
[[Seacas]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41784e113eb3e990f04a2b4ef6d59855471a7981"
os = "windows"

    [[Seacas.download]]
    sha256 = "a4d3a278409c6d6361d386b67b11085c2c9788c329722e8ed72d481eac365980"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.7+0/Seacas.v0.1.7.i686-w64-mingw32-cxx03.tar.gz"
[[Seacas]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc5a6f1aeb435e7a9e09cb8ac801f590e8f63ffe"
os = "windows"

    [[Seacas.download]]
    sha256 = "1363f21da8defe8839a4e83e913d505f99df934eaf1893fd46937e99a23e571f"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.7+0/Seacas.v0.1.7.i686-w64-mingw32-cxx11.tar.gz"
[[Seacas]]
arch = "x86_64"
#git-tree-sha1 = "577c1c09489b435c934ae6f804d9d9c6c1feb9f6"
git-tree-sha1 = "bdcfa28a888f5509515fe0b93b92850910d75d5e"
os = "macos"

    [[Seacas.download]]
    sha256 = "89ea63ca06671ed64b1e07c08cae4aaf786545c93268b24f43b3a9fa91fa9f5f"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.7+0/Seacas.v0.1.7.x86_64-apple-darwin.tar.gz"
[[Seacas]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26170351aef7b0a65195a31bec30e5ecb1f888fd"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "2acdc71ed5e04cd403fb4445aed1928b99da16b93021cade0ee3abde8bc1dfd7"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.7+0/Seacas.v0.1.7.x86_64-linux-gnu-cxx03.tar.gz"
[[Seacas]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad0d48030d95b48a16850d025d310ebd32a03a3e"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "5ecb3b5045a6a637fcbd42abdd2912ae1eb2cbd6aae27cb1a5b77d80e81f915c"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.7+0/Seacas.v0.1.7.x86_64-linux-gnu-cxx11.tar.gz"
[[Seacas]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44f1f3c1cbf9272eb5f56007b5031c2c18513a81"
os = "windows"

    [[Seacas.download]]
    sha256 = "ab4e57ee00012fe7855f9cc632104c1bf08d719d5fdcc5cacc326b6fdac4cc60"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.7+0/Seacas.v0.1.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[Seacas]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5aea968f0a32081806f02d5fad95b70c271b3f70"
os = "windows"

    [[Seacas.download]]
    sha256 = "baedf50e866ad742d93ad04bcd2c75c0bf123a53ddc5b6542463dfef0df86b78"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.7+0/Seacas.v0.1.7.x86_64-w64-mingw32-cxx11.tar.gz"
