[[Seacas]]
arch = "aarch64"
git-tree-sha1 = "ecdd10246a0be6d5a3e510e80dac02e40fe42d50"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "093be950360d092055e54fa80579f34274a9275b238becd878d9829ae956fecc"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.5+0/Seacas.v0.1.5.aarch64-linux-gnu.tar.gz"
[[Seacas]]
arch = "i686"
git-tree-sha1 = "e133ba6c10f2829247240e8de78ed77a712aeeaf"
os = "windows"

    [[Seacas.download]]
    sha256 = "c4dd9384db67b82781a3756cddc2c5f277130771be11960fc18b5322b445e71b"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.5+0/Seacas.v0.1.5.i686-w64-mingw32.tar.gz"
[[Seacas]]
arch = "x86_64"
git-tree-sha1 = "e0449954dd122fe6e55a9af9fc4290aef716769a"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "6fd5352fe542614740ea6f2bbd02546cf29bd3012d9a9844e37b351dab2ab355"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.5+0/Seacas.v0.1.5.x86_64-linux-gnu.tar.gz"
[[Seacas]]
arch = "x86_64"
git-tree-sha1 = "c2c1201e4d6bfc4b46f4c9a0bc459059ca62b3b1"
os = "windows"

    [[Seacas.download]]
    sha256 = "f7dff9304dbbec2b161aa83067c48a37848ef1ac828d5b6a1bb68a31b9e66ea9"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.5+0/Seacas.v0.1.5.x86_64-w64-mingw32.tar.gz"
[[Seacas]]
arch = "aarch64"
git-tree-sha1 = "8c62c783e58ac62d2d77a8d38402d744f00cab77"
os = "macos"

    [[Seacas.download]]
    sha256 = "a106c5d77a016d4a7dff41d21358d491f0345f98b2907fedc3141635c005c1a1"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.6+0/Seacas.v0.1.6.aarch64-apple-darwin.tar.gz"
[[Seacas]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81373a79eca1b9d966f105da2a775361dfd5daed"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "d4adc2b5653ae224a781740a08b7d552e8353cdb538d09a186b48044b9c68481"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.6+0/Seacas.v0.1.6.aarch64-linux-gnu-cxx03.tar.gz"
[[Seacas]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bea9ca120f208a8e23253016fe13782c386e632f"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "6eb39bc771a817c105b6cd24643a6a138ead470e6b3894c65e30addff7ef68fd"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.6+0/Seacas.v0.1.6.aarch64-linux-gnu-cxx11.tar.gz"
[[Seacas]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "063167a168fa278ad7ec5d6c1a8e9a18eb29acc7"
os = "windows"

    [[Seacas.download]]
    sha256 = "1e9a8b42cfb9dab638600c3330c54356fd465cec64380d3b8b966caa9ac5064a"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.6+0/Seacas.v0.1.6.i686-w64-mingw32-cxx03.tar.gz"
[[Seacas]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb8ead7892f180e3cdf85d17936c6a3c37173818"
os = "windows"

    [[Seacas.download]]
    sha256 = "060c39c09f6f4911aaa47cbbee22f8240d670c593ca49e27d8337307d1894cc8"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.6+0/Seacas.v0.1.6.i686-w64-mingw32-cxx11.tar.gz"
[[Seacas]]
arch = "x86_64"
#git-tree-sha1 = "c543cf1873ba8b9f072111bddfe8d413b1fa4ca5"
git-tree-sha1 = "cd16cd06c30565dcc15bcc7040da2acad79a7e6e"
os = "macos"

    [[Seacas.download]]
    sha256 = "292d88842bd3a2b3486960d285f26ac54dc92497f7909ddc75dbbea8aaf18e65"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.6+0/Seacas.v0.1.6.x86_64-apple-darwin.tar.gz"
[[Seacas]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e444c3d5443ace087fbd31a3aa6982d195a042d"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "663afc4df6d8da62be78b5b3ffd5cdb7c7db473c461dccbf85d2686e539a7438"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.6+0/Seacas.v0.1.6.x86_64-linux-gnu-cxx03.tar.gz"
[[Seacas]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c4376a014f03d4edf0dfaaef02d27c40834d667"
libc = "glibc"
os = "linux"

    [[Seacas.download]]
    sha256 = "9483a3dc63c018d1508b868fbd9c2d52871a205dbcc9703b0c249efe74dd87bd"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.6+0/Seacas.v0.1.6.x86_64-linux-gnu-cxx11.tar.gz"
[[Seacas]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50a3fc26e54bec2aecedc413c7c96224b9145c6f"
os = "windows"

    [[Seacas.download]]
    sha256 = "e6bf6636ef697e72e33d50d9bc8dd9d53762ca3dff9682c61da0e7c7815f893e"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.6+0/Seacas.v0.1.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[Seacas]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "375f8e7f46bb07cbf1c4bff943f38bc8492604e6"
os = "windows"

    [[Seacas.download]]
    sha256 = "de2e4e249862fe115ae787624e70f8f0f9f0f30f98e352b9454ce8a2e715a25d"
    url = "https://github.com/cmhamel/Seacas_jll.jl/releases/download/Seacas-v0.1.6+0/Seacas.v0.1.6.x86_64-w64-mingw32-cxx11.tar.gz"
