# Autogenerated wrapper script for Seacas_jll for i686-w64-mingw32
export libexodus

using Zlib_jll
using NetCDF_jll
using HDF5_jll
JLLWrappers.@generate_wrapper_header("Seacas")
JLLWrappers.@declare_library_product(libexodus, "libexodus.dll")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, NetCDF_jll, HDF5_jll)
    JLLWrappers.@init_library_product(
        libexodus,
        "bin\\libexodus.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
